version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pandemik@76"
    ports:
      - "1433:1433"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=SCHOOLAPPDB;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: Spurgeon
      SPRING_DATASOURCE_PASSWORD: Pandemik@76
      CONSUMER_KEY: SPRE2WpFA5yzVEzIFEHMiX4XURsAH9fcypgM3HdilapXV45b
      CONSUMER_SECRET: 0ELGz7HXzuhyrDxg0nHNRxwuMSBqNFen4gc1FxLIrK00PuIM7hA3rGUhf05GXWzp
      SHORTCODE: 174379
      PASS_KEY: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
      ACCESS_TOKEN_URL: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
      PAYMENT_URL: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
      CALLBACK_URL: https://schoolapp-2.onrender.com/api/online-payment/callback
