version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_USER: "Spurgeon"
      MSSQL_PASSWORD: "Pandemik@76"
    ports:
      - "1433:1433"
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - sqlserver
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


